application:
  config:
    profile: dev

server:
  port:8082
spring:
  data:
    mongodb:
      database: accounts
      host: localhost
      port: 27017

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: Spring Boot Actuator Demo
    web: *
  hello: Hi there!!!

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
logging:
  level:
    root: info
  health:
    show-details: always