application:
  config:
    profile: dev

server:
  port: 8081
spring:
  data:
    mongodb:
      database: customers
      host: localhost
      port: 27017
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true